### PR TITLE
Update check_doc.py, clang-format-diff.py, zmq_sub.py, optimize-pngs.py print function syntax

### PR DESCRIPTION
**Pull request by NoNameDude**
Updated python print functions

### CODE REVIEW

**Comment by farsider350** [comment]
If you could add an edit into the credit section of each file as MarcoFalke has done most the previous work here and either way is sufficient imo.
Not needed but happy to sign off once credits are fixed.

**Comment by seanPhill** [comment]
Well, I've satisfied myself that the change is necessary, as in Python2 `print "something"` works, and `print ("something") _also works,_ while in Python3 the former fails and the latter succeeds.

```
Python 2.7.17 (default, Oct  6 2020, 23:05:51) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> print "something"
something
>>> print ("something")
something
>>> 
```

```
Python 3.10.10 (main, Feb  8 2023, 05:44:38) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> print "something"
  File "<stdin>", line 1
    print "something"
    ^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
>>> print ("something")
something
>>> 
```

**Comment by seanPhill** [comment]
> add an edit into the credit section of each file

In order to do this in a concise and standardised way I'm trying to find an example of adding a minor editor in the credits. It doesn't seem to have been done before, except for in release notes.

**Review by seanPhill — APPROVED** [review]
The print functions have been updated to include the required (by Python3) parentheses.
This appears to have become especially important now that default Python has shifted from 2.7 to 3.x. My macOS I see, has recently been updated to run Python3.10 by default, whereas for some years had been running 2.x when invoking python without specifying the version.

**Comment by Twinky-kms** [comment]
In future PRs and commit messages, please be a bit more concise. "Fix code" is very vague. 

A good PR and commit message here would be, Update python print syntax.

**Comment by Twinky-kms** [comment]
Tested ACK

The `check_doc.py`, `clang-format-diff.py`, `zmq_sub.py`, and `optimize-pngs.py`. Scripts are still broken on 3.8+, so 2.7 is still required. However, this change does not break the 2.7 version as it supports both syntaxes for the print function so I've gone ahead and approved this PR.  

In `optimize-pngs.py` you missed a few print functions, I've gone ahead and pushed updated syntax for them.

**Review by Twinky-kms — APPROVED** [review]
Approved.

**Comment by Twinky-kms** [comment]
Once @farsider350 recommendations have been added and approval is given by @farsider350 this will be merged.

**Comment by farsider350** [comment]
We will merge this, add credits to release notes and in future PR's can be made to develop branch.

**Pull request merged**
