### PR TITLE
Remove alert system. Add rescan, setmaxconnections RPC. Checkpoints and Chaindata

### PR DESCRIPTION
**Pull request by farsider350**
This has the benefit of removing a single point of failure/control (because it depends on a keypair to send alerts).
The discussion can be seen here https://github.com/dogecoin/dogecoin/issues/2231 and the commit is found here https://github.com/dogecoin/dogecoin/commit/565280f45779837f1bf905236f1015d9ed90513f

### CODE REVIEW

**Comment by TripleZen** [comment]
Actions tests can be viewed here https://github.com/farsider350/dingocoin/actions/runs/5685372828/job/15410116471

**Comment by farsider350** [comment]
Tests can be viewed here https://github.com/farsider350/dingocoin/actions

**Review by seanPhill — APPROVED** [review]
I've reviewed these commit by commit and I approve these changes.

**Comment by seanPhill** [comment]
Leaving it for a short time in case any other reviewers want to review first.

**Comment by Twinky-kms** [comment]
LGTM

**Comment by seanPhill** [comment]
Merging into dev now. To be merged into master after other PR merged.

**Pull request merged**
